import Head from 'next/head'
import Navbar from '../components/Navbar/Navbar'
import Timeline from '../components/Timeline/Timeline'
import Notifications from '../components/Notifications/Notifications'
import Contacts from '../components/Contacts/Contacts'
import News from '../components/News/News'
import Account from '../components/Account/Account'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Social Network</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main className="flex bg-gray-100 p-6">
        <div className="flex w-1/6 flex-col space-y-4">
          <h1 className="text-sm font-medium uppercase text-gray-400">
            Account
          </h1>
          <Account />
          <h1 className="text-sm font-medium uppercase text-gray-400">News</h1>
          <News />
        </div>

        <Timeline />

        <div className="flex w-1/5 flex-col space-y-4">
          <h1 className="text-sm font-medium uppercase text-gray-400">
            Friend Requests
          </h1>
          <Notifications />
          <h1 className="text-sm font-medium uppercase text-gray-400">
            Contacts
          </h1>
          <Contacts />
        </div>
      </main>
    </div>
  )
}
