import Head from 'next/head'
import Navbar from '../components/Navbar/Navbar'
import Timeline from '../components/Timeline/Timeline'
import Notifications from '../components/Notifications/Notifications'
import Contacts from '../components/Contacts/Contacts'
import News from '../components/News/News'
import Account from '../components/Account/Account'
import { useSession } from 'next-auth/react'

export default function Home() {
  const { data: session } = useSession()

  return (
    <div>
      <Head>
        <title>Woof - The First Social Network for Dogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main className="flex bg-gray-100 p-8">
        <section className="hidden h-screen w-1/5 lg:inline-block">
          <h1 className="pb-2 text-sm font-medium uppercase text-gray-400">
            Account
          </h1>
          <Account />
          <h1 className="pt-8 pb-2 text-sm font-medium uppercase text-gray-400">
            News
          </h1>
          <News />
        </section>

        <section className="h-screen flex-grow pb-44">
          <Timeline />
        </section>
        <section className="hidden h-screen w-1/5 lg:inline-block">
          <h1 className="pb-2 text-sm font-medium uppercase text-gray-400">
            Friend Requests
          </h1>
          <Notifications />
          <h1 className="pt-8 pb-2 text-sm font-medium uppercase text-gray-400">
            Contacts
          </h1>
          <Contacts />
        </section>
      </main>
    </div>
  )
}
